"""Restaurant Migration

Revision ID: 9825eeb9deee
Revises: 
Create Date: 2023-07-25 14:27:50.653724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9825eeb9deee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_constraint('restaurant_ibfk_1', type_='foreignkey')
        batch_op.drop_column('oid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('restaurant_ibfk_1', 'owner', ['oid'], ['oid'])
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
