"""edit customer and owner

Revision ID: b3aa04f1a707
Revises: 7f50321be430
Create Date: 2023-07-25 17:06:44.597620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3aa04f1a707'
down_revision = '7f50321be430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=False)

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.drop_column('username')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
